baseurl = "https://high-rise-blog.pages.dev"
languageCode = "en-us"
title = "In Search of High Rise"
theme = "internet-weblog"
pygmentsstyle = "emacs"
Paginate = 10

[markup.goldmark.renderer]
unsafe=true

[author]
	Handle = "High-Rise"
	FirstName = "Shira"
	LastName = "Nazarian"
	AboutPage = "/about"
	Location = "Planet Earth, USA"
	FlickrID = ""

[params]
	Description = "Internet weblog of Software (Mac, iOS, Web) Developer, Josh Johnson."
	ShowCopyright = true
	RSSEnabled = true
	EnablePreferredDarkAppearance = true
	RSSMicropostTitles = false
	mainSections = [ "posts", "microposts", "photos" ]

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
	name = "Microposts"
	weight = 1
	identifier = "microposts"
	url = "/microposts/"

[[menu.main]]
	name = "Post Archive"
	weight = 2
	identifier = "posts"
	url = "/posts/"

[[menu.main]]
	name = "Photography"
	weight = 3
	identifier = "photoography"
	url = "https://jnjosh.photography"